### ISSUE TITLE
Release on forge

### ISSUE THREAD

**Issue by oxc** [oxc/puppet-rspamd#17]
Please let me know when this module is released on the puppet forge under the new namespace, so I can deprecate the old module.

**Comment by oxc** [comment]
I'm just leaving this here for my convenience :) Carry on...

```
http --json PATCH https://forgeapi.puppet.com/v3/modules/oxc-rspamd "Authorization: Bearer $TOKEN" action=deprecate params:='{"replacement_slug":"markt-rspamd"}'

**Comment by fraenki** [comment]
Released on Puppet Forge:
https://forge.puppet.com/modules/markt/rspamd/

**Comment by oxc** [comment]
Thanks. [oxc-rspamd](https://forge.puppet.com/modules/oxc/rspamd/readme) is now deprecated 😢
