### ISSUE TITLE
Still supported ?

### ISSUE THREAD

**Issue by Yamakasi** [oxc/puppet-rspamd#3]
Is this module still active and supported ?

**Comment by oxc** [comment]
Yes, it is.

**Comment by Yamakasi** [comment]
@oxc that is great, I'm going to use it then!

Are you looking into some more configurations as well ? The basic start is already good but I don't know what manual will affect in this was that we might want to automate as well ?

**Comment by oxc** [comment]
No, the module will most likely not support special sets of configurations. The rspamd configuration is quite massive, and while the defaults are pretty decent, there won't be a "one fits all" kind of setup.

All aspects of the configuration can be handled with this module, I believe everything else should go into profiles. However, if you have a good use-case for a some kind of abstraction, feel free to open an issue for it, of course.
