### ISSUE TITLE
How to set rspamd::config in Foreman ?

### ISSUE THREAD

**Issue by Yamakasi** [oxc/puppet-rspamd#4]
Hi,

As I was planning to use this module I imported it in Foreman and see the parameters under the rspamd class itself I'm not sure how I will include rspamd::config on a host(group) as it's not there because of being a resource.

Any idea about this maybe ?

Thanks again!

Matt

**Comment by oxc** [comment]
You don't include rspamd::config, you include the rspamd class and usually set a value for its $config parameter (which exists since [v1.1.0](https://github.com/oxc/puppet-rspamd/releases/tag/v1.1.0)). This is most likely nothing you do from within Foreman, but I have no first-hand experience on that matter. This configuration should probably go in your hiera data.

**Comment by Yamakasi** [comment]
@oxc yes but to put it in your hiera data you need a resource as parameter, I think it's good to add one and make it compatible.

This is also usefull for other ENC's.

**Comment by oxc** [comment]
@Yamakasi, I don't think that's how it works. You should be able to send a value for $rspamd::config from your ENC, _or_ put the value in your hiera data. 
I'm not sure what else would be needed to accomplish this, can you be more elaborate please?

**Comment by Yamakasi** [comment]
@oxc thanks for the support so far!

I will create a testVM today for it and will let you know what I see and report back, that is always usefull for others in my opinion when we/I figured it out!

**Comment by fraenki** [comment]
@Yamakasi I'm not sure I fully understand where your're heading to... 

In a manifest you would probably use the module as follows:

```
  class { 'rspamd':
    config => {
      antivirus => {
        clamav => {
          servers    => '/var/run/clamav/clamd.sock',
          log_clean => true,
        },
      },
      dkim_signing => {
        allow_username_mismatch => true,
        sign_local                             => true,
      },
      greylist => {
        enabled: false,
      },
    },
  }
```

When using an ENC and Hiera, you'll most likely call the Class `rspamd` in your ENC and put only the `rspamd::config` hash in Hiera:

```
rspamd::config:
  antivirus:
    clamav:
      servers: '/var/run/clamav/clamd.sock'
      log_clean: true
  dkim_signing:
    allow_username_mismatch: true
    sign_local: true
  greylist:
    enabled: false
```

So, to reply to your comments on IRC, there's no need to add another resource... the module will setup everything for you, Hiera is fully supported too:

https://github.com/oxc/puppet-rspamd/blob/39ab7c371d9b8ca0cf668e7c80cd883292f64187/manifests/configuration.pp#L19

**Comment by Yamakasi** [comment]
@fraenki thanks for the explanation. The issue is that you need a parameter to put your yaml in, that parameter is used for the resource. I think the $rspamd::config should be something like $config.

**Comment by fraenki** [comment]
@Yamakasi This is more a question of how to use complex data structures in Foreman. I don't think this is directly related to this module.

**Comment by oxc** [comment]
Well, the parameter is called $config, and it's part of the rspamd class. This makes its canonical name $rspamd::config. I don't know how this would conflict with the name of the rspamd::config resource.

I agree with @fraenki, this seems to be an issue with using Foreman to specify data, nothing related specifically to this module. I'm closing this again, until proven otherwise.

**Comment by Yamakasi** [comment]
@fraenki @oxc Yes I agree but I'm trying to find a general way which suits for mostly all modules.

**Comment by Yamakasi** [comment]
@fraenki @oxc It's very OK! I was still on 1.0.2 it seems and upgraded and found the $config parameter so now I'm going to play with it!

Thanks a lot for keeping me focussed!

**Comment by oxc** [comment]
@Yamakasi glad you figured it out. If only someone had mentioned the version requirement in the first comment ;) *scnr*
