### ISSUE TITLE
Example to "overwrite" workers in rspamd.conf

### ISSUE THREAD

**Issue by Yamakasi** [oxc/puppet-rspamd#5]
I'm trying to (re)config the default workers in rspamd.conf, for an example:

```
worker "controller" {
#    bind_socket = "localhost:11334";
    bind_socket = "xx.xx.xx.xx:11334";
    .include "$CONFDIR/worker-controller.inc"
    .include(try=true; priority=1,duplicate=merge) "$LOCAL_CONFDIR/local.d/worker-controller.inc"
    .include(try=true; priority=10) "$LOCAL_CONFDIR/override.d/worker-controller.inc"
}
```

I'm not really seeing how to accomplish this without messing up the default config, can you help me out with this to get a better overview of this "controller" one ?

The rest of the files it pretty straight forward.

Thanks again!

**Comment by oxc** [comment]
This one is pretty straight-forward as well. Please note that this is not a support forum, and that in order to use this module you must understand how rspamd configuration works (and you really should read the provided module documentation).

**Comment by Yamakasi** [comment]
@oxc I know how the config works but this was not fully clear. The commit helps to make it more understandable.

Sure this is no forum but when the module is not fully clear about something it should be noticed, I did, you took good and useful action on it, why see it as a further problem ?

I love see to questions when some people are not sure about something, it could be others are not as well, it keeps us focussed!

Thanks again!
