### ISSUE TITLE
puppetlabs-stdlib dependency very restrictive

### ISSUE THREAD

**Issue by adenau** [oxc/puppet-rspamd#9]
The following dependency :

puppetlabs-stdlib (>= 4.16.0 < 5.0.0)

Is very restrictive. Some other modules I have require stdlib to be >5.0.0 (for example : https://forge.puppet.com/modules/puppetlabs/accounts/dependencies).

Would it be possible if your module could support stdlib up to 7.0.0?

Thanks,

**Comment by oxc** [comment]
Fixed in #8
